### PR TITLE
Added some missing prop-types

### PR DESCRIPTION
**Pull request by resir014**
This should fix most of the green linter warnings.

### CODE REVIEW

**Comment by resir014** [comment]
@dtinth Also, is it just me or is the linter not working on my end?

image

**Comment by dtinth** [comment]
Wow, thanks!!

I got the same linter issue, but I don’t understand why it’s causing an error locally but not on CI right now. I will have to investigate later.

**Comment by resir014** [comment]
@dtinth Ah, I see now. I'll look into more PropTypes stuff tomorrow.

By the way, happy new year!! :D

**Comment by dtinth** [comment]
Happy new year from Thailand!

Thanks a lot for helping to improve this project.

I submitted the Bemuse project for inclusion in React examples:
https://github.com/reactjs/reactjs.org/pull/475

Best wishes for the new year.

:D

**Comment by resir014** [comment]
@dtinth Alright, all of these should be finished. No more green linter errors!

Also, putting this on the same PR since it's late, but I did fix [the "Script error" issue](https://github.com/bemusic/bemuse/pull/459/commits/9624e94aa5667524379310ad49f27387a6f78418) while clicking the social media links.

**Comment by resir014** [comment]
Welp, found an issue. LoadingSceneProgressBar, the `value` prop seems like it should be passed a `string` or `number`, but somewhere in the app is passing percentage values as `75%` (not as string, nor a number).

**Comment by dtinth** [comment]
By the way, would you like to become a collaborator on this project?

**Comment by resir014** [comment]
> By the way, would you like to become a collaborator on this project?

Yeah, sure!

And just to let you know I'm planning to tackle [refactoring the loader](https://github.com/bemusic/bemuse/issues/452) now that this PR is merged.

**Comment by dtinth** [comment]
Woah, cool thanks!

I’ll add you promptly.

**Pull request merged**
