### PR TITLE
Get everything to work on React 16

### PR DESCRIPTION
**Pull request by resir014**
...hopefully.

Reference: #437 

Left this PR up in case there are some feedback available throughout this process. Current issue:

image

Found several deps which only supports `peerDependencies` up to React 15:

* `react-overlay-popup`
* `react-warp-portal`

### CODE REVIEW

**Comment by resir014** [comment]
@dtinth On closer inspection, it might just be because `react-warp-portal` uses `React.createClass()`:
https://github.com/taskworld/react-warp-portal/blob/master/src/createWarp.js#L17

**Comment by dtinth** [comment]
`react-overlay-popup` is unused, and React 16 has first-class portal support now, albeit with a different API:

https://reactjs.org/docs/portals.html

**Comment by resir014** [comment]
@dtinth `react-overlay-popup` has been removed. And this is the first time I've heard about portals in React, lol. I'll have a look at it tomorrow.

**Comment by resir014** [comment]
@dtinth It's alive!

I'll test if everything works when I leave work. Also, Travis now tests via Node 6 and 8. I haven't had any luck to upgrade the CircleCI environment without any errors, so I'll let you figure that one out.

**Pull request merged**
