### PR TITLE
fix non A-Z vars in JS code

### PR DESCRIPTION
**Pull request by abbychau**
as title

### CODE REVIEW

**Comment by dtinth** [comment]
The 川 sign in the code is a signature that denotes a stream, i.e., an observable.

```js
const songTitle川 = song川.map(song => song.title)
```

You can see that `song川` represents a stream of song over time, but if you want to manipulate individual song inside a stream, we used the variable name `song`. This makes it easier to differentiate between a stream vs. a plain data object.

**Comment by abbychau** [comment]
I see. Thank you very much for the information.
How about bus?

**Comment by dtinth** [comment]
口 means mouth. I use this character to represent an object where things can be shoved into it. 😮

A `Bacon.Bus` is one such example. 😄

I like to use these characters because:

- They are easy to scan.
- They already has meaning on its own (川 is river, 口 is mouth).

Other approaches are:

- Using symbols such as `$` for streams (like `song$`), but the `$` doesn’t have a default intuitive meaning (usually it means dollars).
- Appending words such as `Stream` (like `songStream`), this makes the variable name needlessly long.
- Go hungarian notation and prefix with short characters (like `stSong`), this makes the name not pronounceable, and it can be confusing (`st` stands for string or stream?).

**Comment by abbychau** [comment]
I see! I never connect that mouth can be something like a slot or socket!
That's bold to use non standard ascii characters in the naming of variables, but I do understand and love it.
I will close the request then. 

P.S. I love the way you use circleCI and you blog is interesting too. (I love music games and played O2Jam and DjMAX and PIU before too)

**Pull request closed without merging**
