### PR TITLE
[React16] Convert React.PropTypes to PropTypes

### PR DESCRIPTION
**Pull request by resir014**
Reference: #437

Migrate the deprecated `React.PropTypes` to `prop-types`. Initial baby steps on migrating the entire codebase to React 16

### CODE REVIEW

**Comment by dtinth** [comment]
Could you fix the linter warnings (above)?

**Comment by resir014** [comment]
@dtinth Will do. Do you want me to merge the latest `master` changes back here as well?

**Comment by dtinth** [comment]
@resir014 That would be great, thanks!

**Comment by resir014** [comment]
Okay, it's done! Waiting for CI to catch up.

**Comment by dtinth** [comment]
Thanks for your contributions!

**Pull request merged**
