### PR TITLE
:arrow_up: Deps upgrade - v42 edition

### PR DESCRIPTION
**Pull request by resir014**
Some more upgrades for our dependencies + devDependencies.

### CODE REVIEW

**Comment by dtinth** [comment]
I am fixing the merge conflicts.

**Comment by resir014** [comment]
Cool. It might be also safe to rebuild the `yarn.lock` on the PR too.

**Comment by dtinth** [comment]
(I am fixing the merge conflicts in this PR.)

**Comment by dtinth** [comment]
@resir014 You mean, rebuild `yarn.lock` from scratch?

**Comment by resir014** [comment]
Actually nevermind. I just realised it's been done on the other PR :sweat_smile:

**Comment by dtinth** [comment]
I am having trouble with the internet connection right now (`yarn install` won’t finish and stuck at building puppeteer), so I reverted `yarn.lock` to current `master` for now.

That means before merging, we have to run `yarn.lock` (either rebuild from scratch or using the `master` version) to update it.

**Comment by resir014** [comment]
Okay, take your time. I'm probably be out all day today as well and will be
back on my computer later tonight.

**Comment by dtinth** [comment]
Thanks! I think we can merge this now.

- After Babel 7 is added, somehow, Danger stops working because it tries to use Babel 6 to transpile ES6 code. Our Babel config references plugins that only works with Babel 7, thus crashing Danger. Upgrading to latest Danger fixes it.

- Seems like Prettier now uses `-` instead of `*` for list items, so that’s why the README file has to be updated too.

**Pull request merged**
