### PR TITLE
Updated Windows development guide

### PR DESCRIPTION
**Pull request by resir014**
Updating the Windows development guide, since I work with Windows most of the time. I'm trying to make this as workflow-agnostic as possible (some people still prefer working with the GUI over the command line).

### CODE REVIEW

**Comment by resir014** [comment]
@dtinth You're welcome!

Also, the docs doesn't seem to be built since v37. o:

**Comment by dtinth** [comment]
Yeah... It seems like the build environment over there changed somehow... It failed without any logs T_T https://readthedocs.org/projects/bemuse/builds/6558283/

**Comment by resir014** [comment]
@dtinth Here are the errors that I got locally:

image

**Comment by resir014** [comment]
@dtinth I did another investigation and it seems to be a plugin issue. Removing the `bemuse` plugin seems to have fixed the doc generation.

image

Unfortunately, I have absolutely no Python experience, so I can't help you with fixing the plugin ;-; Although I could assist should you want to migrate to another doc generation system. [Gitbook](https://www.gitbook.com/) is one of the very few alternatives, but is somewhat a little outdated and lacks the features that the bemuse docs uses. :c (it does support MathJax equations, but I can't get it to work properly)

**Comment by dtinth** [comment]
@resir014 I see. Thanks for helping investigating this!

Yeah, there is some custom code that has to do with generating docs from the source code. I plan to remove it and just use normal Markdown-style docs in the future. Maybe even just link it to GitHub and generate svg/png files for the maths we use, so that maintenance cost is minimized.

We need to set up redirects from readthedocs to the new docs system, though.

**Comment by resir014** [comment]
@dtinth If we're just doing markdown + images, then running a selfhosted
Gitbook will work. If we could move production hosting of Bemuse over to
Netlify as well, then essentially we could use the `.github.io` domain as
our docs page.

**Comment by dtinth** [comment]
GitBook sounds great!

We can also adjust our build script to also build the GitBook into `dist/docs` directory, so that the docs can be deployed along with the game (e.g. at bemuse\.ninja/docs).

By the way, Facebook also published https://docusaurus.io/.

**Comment by resir014** [comment]
> By the way, Facebook also published https://docusaurus.io/.

I've heard about Docusaurus! I'm giving it a try as well.

**Pull request merged**
